### ISSUE TITLE
Bump toml dependency

### ISSUE THREAD

**Issue by hoefling** [darrenburns/ward#164]
Adding `ward` and `taskipy` yield a version conflict:

```toml
[tool.poetry.dev-dependencies]
ward = "^0.46.0-beta.0"
taskipy = "^1.2.1"
```
Log:
```sh
$ poetry install
Updating dependencies
Resolving dependencies... (3.0s)

[SolverProblemError]
Because no versions of taskipy match >1.2.1,<2.0.0
 and taskipy (1.2.1) depends on toml (>=0.10.0,<0.11.0), taskipy (>=1.2.1,<2.0.0) requires toml (>=0.10.0,<0.11.0).
And because ward (0.46.0b0) depends on toml (>=0.9.4,<0.10.0)
 and no versions of ward match >0.46.0-beta.0,<0.47.0, taskipy (>=1.2.1,<2.0.0) is incompatible with ward (>=0.46.0-beta.0,<0.47.0).
So, because thesis depends on both ward (^0.46.0-beta.0) and taskipy (^1.2.1), version solving failed.
```
