### ISSUE TITLE
Strict configuration

### ISSUE THREAD

**Issue by hukkin** [darrenburns/ward#270]
It seems I can do stuff like
```toml
[tool.ward]
lol = "roflmao"
```

or worse, minor typos 
```toml
[tool.ward]
ordet = "random"
```

I'd like to propose making Ward error hard on invalid configuration (and print the name of the invalid conf option).
